name: "CAN-Battery-Emulator"
description: "Home Assistant CAN Battery Emulator"
version: "1.1.3"
slug: "can-battery-emulator"
url: "https://github.com/webbbn/ha-can-battery-emulator/tree/main/can-battery-emulator/"
init: false
host_dbus: true
host_network: true
homeassistant_api: true
hassio_api: true
image: "ghcr.io/webbbn/{arch}-addon-can-battery-emulator"

arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

services:
  - mqtt:need

discovery:
  - mqtt

options:
  interface: "socketcan"
  device: "can0"
  baudrate: 500000
  verbose_log: false
  log_interval: 10.0
  sample_period: 2.0
  expire_values_after: 20

  # Battery options (Default for 16S)
  bat_modules: 1
  charge_volts: 53.6
  absorption_volts: 55.2
  min_voltage: 45.0
  rebulk_offset: 0.6
  charge_current: 50.0
  discharge_current: 100.0

  # MQTT Options
  mqtt_user: 'hass'
  mqtt_password: 'password'
  mqtt_broker: 'homeassistant'
  mqtt_port: 1883

  # MQTT Topics
  voltage_topic: "victron/soc/total_voltage"
  current_topic: "victron/soc/current"
  soc_topic: "victron/soc/soc_percent"
  power_topic: "victron/soc/power"

schema:
  interface: "str"
  device: "str"
  verbose_log: "bool?"
  log_interval: "float?"
  sample_period: "float?"
  expire_values_after: "float?"

  # Battery Options
  bat_modules: "int(1,3)"
  charge_volts: "float(0,100)"
  absorption_volts: "float(0,100)"
  min_voltage: "float(0,100)"
  rebulk_offset: "float(0,100)"
  charge_current: "float(0,500)"
  discharge_current: "float(0,500)"

  # MQTT Options
  mqtt_user: "str"
  mqtt_password: "str"
  mqtt_broker: "str"
  mqtt_port: "int(1,65535)?"

  # MQTT Topics
  voltage_topic: "str"
  current_topic: "str"
  soc_topic: "str"
  power_topic: "str"
